### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by acoiro**
Hey guys,

I refactored a few methods and added the ability to automatically handle DOM elements added with JavaScript (after window.onLoad).

I also replaced the class `buffer-share` with the data attribute `data-buffer-share`, it's more consistent in my opinion.

```
<a data-buffer-share
data-url='http://blog.bufferapp.com' 
data-text="The Buffer Blog!" 
data-preferred-login="twitter" 
data-partner-source='feedly' 
data-partner-placement='mini' 
data-via='sunils34'>Share to Buffer</a>
```

Feedback are welcome!

### CODE REVIEW

**Comment by sunils34** [comment]
Hi @acoiro, thanks so much for sending off this pull request. I do like the change you've made which automatically supports elements created through js after the page load.  

Overall, I really like these changes, however this would break backwards compatibility if we change the trigger from class='buffer-share' to data-buffer-share.   If you can add this support I think this might be good to merge in :)

**Comment by acoiro** [comment]
You are welcome!

Thanks for the feedback, I added support for backwards compatibility as requested.

Let me know if you need other changes ;-)

**Comment by sunils34** [comment]
Hi @acoiro.  Thanks for making those improvements so quickly :).  I've gone ahead and accepted the pull request and bumped up the versioning.  

Thanks a ton for helping out with this!

**Comment by acoiro** [comment]
You are welcome, I'm glad you liked my changes!

Don't forget to update the version inside the `package.json` file ;-)

**Pull request merged**
